from database import SessionLocal, engine
import models

models.Base.metadata.create_all(bind=engine)

db = SessionLocal()

frases = [
    # Samurai
    {"texto": "The wind does not forget what man abandons.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "The sword does not make the warrior, the heart does.", "autor": "Japanese Proverb", "categoria": "Samurai"},
    {"texto": "Even the cherry blossom falls with dignity.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "Do not seek victory, seek to be worthy of it.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "The warrior who has never lost does not know true victory.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "To die with honor is to live forever.", "autor": "Bushido", "categoria": "Samurai"},
    {"texto": "The mind of the warrior is like water, formless and limitless.", "autor": "Miyamoto Musashi", "categoria": "Samurai"},
    {"texto": "The way of the warrior is resolute acceptance of death.", "autor": "Yamamoto Tsunetomo", "categoria": "Samurai"},
    {"texto": "A samurai without a lord is like wind without direction.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "Victory belongs to the most persevering.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "Steel is forged in fire, the warrior in adversity.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "The wise warrior attacks with the mind before the sword.", "autor": "Sun Tzu", "categoria": "Samurai"},
    {"texto": "Know your enemy and know yourself.", "autor": "Sun Tzu", "categoria": "Samurai"},
    {"texto": "Honor is not inherited, it is earned.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "The life of a warrior is as brief as the cherry blossom.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "A warrior dies once, a coward dies a thousand times.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "Patience is the strongest armor.", "autor": "Japanese Proverb", "categoria": "Samurai"},
    {"texto": "The true warrior needs no proof of his strength.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "Knowing when not to fight is the warrior's greatest skill.", "autor": "Miyamoto Musashi", "categoria": "Samurai"},
    {"texto": "The way of the sword begins with mastery of oneself.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "Loyalty is the soul of bushido.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "Fear is only a shadow, face the light.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "The katana is the extension of the samurai's soul.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "A sword unused never learns to cut.", "autor": "Anonymous", "categoria": "Samurai"},
    {"texto": "The greatest victory is the one that requires no battle.", "autor": "Sun Tzu", "categoria": "Samurai"},
    # Philosophy
    {"texto": "Silence is the armor of the wise.", "autor": "Japanese Proverb", "categoria": "Philosophy"},
    {"texto": "I know that I know nothing.", "autor": "Socrates", "categoria": "Philosophy"},
    {"texto": "I think, therefore I am.", "autor": "René Descartes", "categoria": "Philosophy"},
    {"texto": "The unexamined life is not worth living.", "autor": "Socrates", "categoria": "Philosophy"},
    {"texto": "Man is the measure of all things.", "autor": "Protagoras", "categoria": "Philosophy"},
    {"texto": "We are what we repeatedly do.", "autor": "Aristotle", "categoria": "Philosophy"},
    {"texto": "The only true wisdom is knowing you know nothing.", "autor": "Socrates", "categoria": "Philosophy"},
    {"texto": "To be is to be perceived.", "autor": "George Berkeley", "categoria": "Philosophy"},
    {"texto": "God is dead, and we have killed him.", "autor": "Nietzsche", "categoria": "Philosophy"},
    {"texto": "That which does not kill us makes us stronger.", "autor": "Nietzsche", "categoria": "Philosophy"},
    {"texto": "Hell is other people.", "autor": "Jean-Paul Sartre", "categoria": "Philosophy"},
    {"texto": "Man is condemned to be free.", "autor": "Jean-Paul Sartre", "categoria": "Philosophy"},
    {"texto": "The soul is the form of the body.", "autor": "Aristotle", "categoria": "Philosophy"},
    {"texto": "One cannot step into the same river twice.", "autor": "Heraclitus", "categoria": "Philosophy"},
    {"texto": "Everything flows, nothing stands still.", "autor": "Heraclitus", "categoria": "Philosophy"},
    {"texto": "The only constant is change.", "autor": "Heraclitus", "categoria": "Philosophy"},
    {"texto": "Happiness is the meaning and purpose of life.", "autor": "Aristotle", "categoria": "Philosophy"},
    {"texto": "To do is to be.", "autor": "Socrates", "categoria": "Philosophy"},
    {"texto": "The measure of a man is what he does with power.", "autor": "Plato", "categoria": "Philosophy"},
    {"texto": "Courage is knowing what not to fear.", "autor": "Plato", "categoria": "Philosophy"},
    {"texto": "At his best, man is the noblest of animals.", "autor": "Aristotle", "categoria": "Philosophy"},
    {"texto": "Wonder is the beginning of wisdom.", "autor": "Socrates", "categoria": "Philosophy"},
    {"texto": "The mind is not a vessel to be filled but a fire to be kindled.", "autor": "Plutarch", "categoria": "Philosophy"},
    {"texto": "In the middle of difficulty lies opportunity.", "autor": "Albert Einstein", "categoria": "Philosophy"},
    {"texto": "Reality is merely an illusion, albeit a very persistent one.", "autor": "Albert Einstein", "categoria": "Philosophy"},
    # Motivation
    {"texto": "The secret of getting ahead is getting started.", "autor": "Mark Twain", "categoria": "Motivation"},
    {"texto": "It does not matter how slowly you go as long as you do not stop.", "autor": "Confucius", "categoria": "Motivation"},
    {"texto": "Everything you have ever wanted is on the other side of fear.", "autor": "George Addair", "categoria": "Motivation"},
    {"texto": "Success is not final, failure is not fatal.", "autor": "Winston Churchill", "categoria": "Motivation"},
    {"texto": "The harder you work, the luckier you get.", "autor": "Gary Player", "categoria": "Motivation"},
    {"texto": "Don't watch the clock, do what it does. Keep going.", "autor": "Sam Levenson", "categoria": "Motivation"},
    {"texto": "The best time to plant a tree was 20 years ago. The second best time is now.", "autor": "Chinese Proverb", "categoria": "Motivation"},
    {"texto": "You miss 100% of the shots you don't take.", "autor": "Wayne Gretzky", "categoria": "Motivation"},
    {"texto": "Whether you think you can or you think you can't, you're right.", "autor": "Henry Ford", "categoria": "Motivation"},
    {"texto": "The only way to do great work is to love what you do.", "autor": "Steve Jobs", "categoria": "Motivation"},
    {"texto": "Life is what happens when you're busy making other plans.", "autor": "John Lennon", "categoria": "Motivation"},
    {"texto": "Spread love everywhere you go.", "autor": "Mother Teresa", "categoria": "Motivation"},
    {"texto": "When you reach the end of your rope, tie a knot and hang on.", "autor": "Franklin D. Roosevelt", "categoria": "Motivation"},
    {"texto": "Always remember that you are absolutely unique.", "autor": "Margaret Mead", "categoria": "Motivation"},
    {"texto": "Do not go where the path may lead, go instead where there is no path.", "autor": "Ralph Waldo Emerson", "categoria": "Motivation"},
    {"texto": "You will face many defeats in life, but never let yourself be defeated.", "autor": "Maya Angelou", "categoria": "Motivation"},
    {"texto": "The future belongs to those who believe in the beauty of their dreams.", "autor": "Eleanor Roosevelt", "categoria": "Motivation"},
    {"texto": "Tell me and I forget. Teach me and I remember. Involve me and I learn.", "autor": "Benjamin Franklin", "categoria": "Motivation"},
    {"texto": "The best revenge is massive success.", "autor": "Frank Sinatra", "categoria": "Motivation"},
    {"texto": "An unexamined life is not worth living.", "autor": "Socrates", "categoria": "Motivation"},
    {"texto": "Spread your wings and let the fairy in you fly.", "autor": "Anonymous", "categoria": "Motivation"},
    {"texto": "When one door of happiness closes, another opens.", "autor": "Helen Keller", "categoria": "Motivation"},
    {"texto": "It is during our darkest moments that we must focus to see the light.", "autor": "Aristotle", "categoria": "Motivation"},
    {"texto": "Do not wait to strike till the iron is hot, but make it hot by striking.", "autor": "William Butler Yeats", "categoria": "Motivation"},
    {"texto": "Great minds discuss ideas, average minds discuss events, small minds discuss people.", "autor": "Eleanor Roosevelt", "categoria": "Motivation"},
    # Japanese Proverbs
    {"texto": "Fall seven times, stand up eight.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "The nail that sticks out gets hammered down.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "Vision without action is a daydream. Action without vision is a nightmare.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "Even monkeys fall from trees.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "The reputation of a thousand years may be determined by the conduct of one hour.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "One kind word can warm three winter months.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "If you understand everything, you must be misinformed.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "A frog in a well does not know the great sea.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "The bamboo that bends is stronger than the oak that resists.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "Better to be a warrior in a garden than a gardener in a war.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "When the character of a man is not clear to you, look at his friends.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "A good sword is the one left in its scabbard.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "The reverse side also has a reverse side.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "Darkness reigns at the foot of the lighthouse.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "Beginning is easy, continuing is hard.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "None of us is as smart as all of us.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "The tongue is but three inches long, yet it can kill a man six feet tall.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "To know and to act are one and the same.", "autor": "Samurai Maxim", "categoria": "Japanese Proverb"},
    {"texto": "Obstacles are the cost of greatness.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "Time spent laughing is time spent with the gods.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "The go-getter catches more fish than the net.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "Even a sheet of paper has two sides.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "A wise man neither says all he thinks, nor thinks all he says.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "Limit your wants and you will have everything you need.", "autor": "Japanese Proverb", "categoria": "Japanese Proverb"},
    {"texto": "The strongest of all warriors are these two: Time and Patience.", "autor": "Leo Tolstoy", "categoria": "Japanese Proverb"},
    # Stoicism
    {"texto": "You have power over your mind, not outside events.", "autor": "Marcus Aurelius", "categoria": "Stoicism"},
    {"texto": "The obstacle is the way.", "autor": "Marcus Aurelius", "categoria": "Stoicism"},
    {"texto": "We suffer more in imagination than in reality.", "autor": "Seneca", "categoria": "Stoicism"},
    {"texto": "He who fears death will never do anything worth of a man who is alive.", "autor": "Seneca", "categoria": "Stoicism"},
    {"texto": "Waste no more time arguing what a good man should be, be one.", "autor": "Marcus Aurelius", "categoria": "Stoicism"},
    {"texto": "The happiness of your life depends upon the quality of your thoughts.", "autor": "Marcus Aurelius", "categoria": "Stoicism"},
    {"texto": "If it is not right, do not do it. If it is not true, do not say it.", "autor": "Marcus Aurelius", "categoria": "Stoicism"},
    {"texto": "It is not the man who has too little, but the man who craves more, that is poor.", "autor": "Seneca", "categoria": "Stoicism"},
    {"texto": "Do not indulge in dreams of what you do not have.", "autor": "Marcus Aurelius", "categoria": "Stoicism"},
    {"texto": "The first rule is to keep an untroubled spirit.", "autor": "Marcus Aurelius", "categoria": "Stoicism"},
    {"texto": "Accept the things to which fate binds you.", "autor": "Marcus Aurelius", "categoria": "Stoicism"},
    {"texto": "Make the best use of what is in your power.", "autor": "Epictetus", "categoria": "Stoicism"},
    {"texto": "No man is free who is not master of himself.", "autor": "Epictetus", "categoria": "Stoicism"},
    {"texto": "Seek not the good in external things, seek it in yourself.", "autor": "Epictetus", "categoria": "Stoicism"},
    {"texto": "Man is not worried by real problems so much as by imagined anxieties.", "autor": "Epictetus", "categoria": "Stoicism"},
    {"texto": "The more we value things outside our control, the less control we have.", "autor": "Epictetus", "categoria": "Stoicism"},
    {"texto": "Luck is what happens when preparation meets opportunity.", "autor": "Seneca", "categoria": "Stoicism"},
    {"texto": "Begin at once to live, and count each separate day as a separate life.", "autor": "Seneca", "categoria": "Stoicism"},
    {"texto": "Life is long if you know how to use it.", "autor": "Seneca", "categoria": "Stoicism"},
    {"texto": "He suffers more than necessary who suffers before it is necessary.", "autor": "Seneca", "categoria": "Stoicism"},
    {"texto": "Confine yourself to the present.", "autor": "Marcus Aurelius", "categoria": "Stoicism"},
    {"texto": "Very little is needed to make a happy life.", "autor": "Marcus Aurelius", "categoria": "Stoicism"},
    {"texto": "Loss is nothing else but change, and change is nature's delight.", "autor": "Marcus Aurelius", "categoria": "Stoicism"},
    {"texto": "Do what nature requires, set out immediately if possible.", "autor": "Marcus Aurelius", "categoria": "Stoicism"},
    {"texto": "The best revenge is to be unlike him who performed the injury.", "autor": "Marcus Aurelius", "categoria": "Stoicism"},
    # Zen
    {"texto": "Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water.", "autor": "Zen Proverb", "categoria": "Zen"},
    {"texto": "The quieter you become, the more you can hear.", "autor": "Ram Dass", "categoria": "Zen"},
    {"texto": "Wherever you are, be there totally.", "autor": "Eckhart Tolle", "categoria": "Zen"},
    {"texto": "If you are depressed you are living in the past. If you are anxious you are living in the future.", "autor": "Lao Tzu", "categoria": "Zen"},
    {"texto": "A journey of a thousand miles begins with a single step.", "autor": "Lao Tzu", "categoria": "Zen"},
    {"texto": "When you realize nothing is lacking, the whole world belongs to you.", "autor": "Lao Tzu", "categoria": "Zen"},
    {"texto": "Nature does not hurry, yet everything is accomplished.", "autor": "Lao Tzu", "categoria": "Zen"},
    {"texto": "Knowing others is wisdom. Knowing yourself is enlightenment.", "autor": "Lao Tzu", "categoria": "Zen"},
    {"texto": "To the mind that is still, the whole universe surrenders.", "autor": "Lao Tzu", "categoria": "Zen"},
    {"texto": "Life is a balance of holding on and letting go.", "autor": "Rumi", "categoria": "Zen"},
    {"texto": "Do not seek the truth, only cease to cherish opinions.", "autor": "Zen Proverb", "categoria": "Zen"},
    {"texto": "The present moment is the only moment available to us.", "autor": "Thich Nhat Hanh", "categoria": "Zen"},
    {"texto": "Smile, breathe, and go slowly.", "autor": "Thich Nhat Hanh", "categoria": "Zen"},
    {"texto": "The flower that blooms in adversity is the rarest of all.", "autor": "Zen Proverb", "categoria": "Zen"},
    {"texto": "Empty your mind, be formless, shapeless like water.", "autor": "Bruce Lee", "categoria": "Zen"},
    {"texto": "When you try to stay on the surface of the water, you sink. When you try to sink, you float.", "autor": "Zen Proverb", "categoria": "Zen"},
    {"texto": "Not thinking about anything is Zen. Once you know this, walking, sitting, or lying down, everything you do is Zen.", "autor": "Bodhidharma", "categoria": "Zen"},
    {"texto": "In the beginner's mind there are many possibilities. In the expert's mind there are few.", "autor": "Shunryu Suzuki", "categoria": "Zen"},
    {"texto": "Let go or be dragged.", "autor": "Zen Proverb", "categoria": "Zen"},
    {"texto": "The obstacle in the path becomes the path.", "autor": "Zen Proverb", "categoria": "Zen"},
    {"texto": "If you miss the present moment, you miss your appointment with life.", "autor": "Thich Nhat Hanh", "categoria": "Zen"},
    {"texto": "When walking, walk. When eating, eat.", "autor": "Zen Proverb", "categoria": "Zen"},
    {"texto": "No snowflake ever falls in the wrong place.", "autor": "Zen Proverb", "categoria": "Zen"},
    {"texto": "What you think, you become. What you feel, you attract. What you imagine, you create.", "autor": "Buddha", "categoria": "Zen"},
    {"texto": "Peace comes from within. Do not seek it without.", "autor": "Buddha", "categoria": "Zen"},
]

for f in frases:
    nueva = models.Frase(
        texto=f["texto"],
        autor=f["autor"],
        categoria=f["categoria"],
        api_key="seed"
    )
    db.add(nueva)

db.commit()
db.close()
print(f"Done! {len(frases)} quotes inserted.")